version: '3'

services:
  app:
    build: ./
    image: sp/app
    environment:
      PORT: 3000
      NODE_ENV: development
    volumes:
      - ./:/src
    ports:
      - '3000:3000'
    command: run server
